unlet! g:skip_defaults_vim
silent! source $VIMRUNTIME/defaults.vim

set shell=/bin/sh

augroup MyVimrc
  autocmd!
augroup END
command! -nargs=* AutoCmd autocmd MyVimrc <args>

if has('vim_starting')
  let g:startuptime = reltime()
  AutoCmd VimEnter * let g:startuptime = reltime(g:startuptime) | redraw
  \ | echomsg 'startuptime: ' . reltimestr(g:startuptime)
endif


runtime! options.vim
runtime! theme.vim
runtime! autocmd.vim
runtime! functions.vim
runtime! mappings.vim
runtime! completion.vim
runtime! highlight.vim
runtime! list.vim
runtime! experiments.vim

for s:f in glob('~/.vim/p-*.vim', 0, 1)
  execute 'source ' . s:f
endfor
